  CREATE TABLE "DBO"."AMP_AGT_AGENT" 
   (	"AGENTID" NUMBER(10,0) NOT NULL ENABLE, 
	"AGENTNUMBER" NVARCHAR2(20), 
	"CONTACTBASEID" NUMBER(10,0) NOT NULL ENABLE, 
	"FROMDATE" TIMESTAMP (3) DEFAULT (systimestamp) NOT NULL ENABLE, 
	"OLDNUMBERS" VARCHAR2(50 BYTE), 
	"ISDIRECTSALES" NUMBER(1,0) DEFAULT ((0))
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "SYSTEM" ;
