  CREATE TABLE "DBO"."AMP_AGT_AGENTHIERARCHY" 
   (	"AGENTHIERARCHYID" NUMBER(10,0) NOT NULL ENABLE, 
	"AGENTID" NUMBER(10,0) NOT NULL ENABLE, 
	"AGENCYID" NUMBER(10,0) NOT NULL ENABLE, 
	"PARENTAGENTID" NUMBER(10,0), 
	"FORWARDADDRESS" NUMBER(1,0) DEFAULT ((0)) NOT NULL ENABLE, 
	"MAILINGCODE" NUMBER(10,0) NOT NULL ENABLE, 
	"BILLINGMAILINGCODE" NUMBER(10,0) NOT NULL ENABLE, 
	"NEWBUSINESSMAILINGCODE" NUMBER(10,0) DEFAULT ((1889)) NOT NULL ENABLE, 
	"EOBMAILINGCODE" NUMBER(10,0) DEFAULT ((1889)) NOT NULL ENABLE, 
	"STATUSID" NUMBER(10,0) NOT NULL ENABLE, 
	"PAYMENTMETHODID" NUMBER(10,0) NOT NULL ENABLE, 
	"MINCOMMPAYMENTAMOUNT" NUMBER(18,2) DEFAULT ((0)), 
	"HOLDCOMMISSIONNB" NUMBER(1,0) DEFAULT ((0)) NOT NULL ENABLE, 
	"HOLDCOMMISSIONRN" NUMBER(1,0) DEFAULT ((0)) NOT NULL ENABLE, 
	"HOLDCOMMISSIONMA" NUMBER(1,0) DEFAULT ((0)) NOT NULL ENABLE, 
	"FROMDATE" TIMESTAMP (3) NOT NULL ENABLE, 
	"TODATE" TIMESTAMP (3), 
	"LEGACYAGENTID" NUMBER(10,0), 
	"WEBPROFILEID" NUMBER(10,0) DEFAULT ((4)) NOT NULL ENABLE, 
	"HOLDCOMMISSIONGEN" NUMBER(1,0) DEFAULT ((0)) NOT NULL ENABLE, 
	"WEBCLAIMSUBMISSIONACCESS" NUMBER(1,0) DEFAULT ((0)) NOT NULL ENABLE, 
	"ISAUTOEMISION" NUMBER(1,0) DEFAULT ((0)) NOT NULL ENABLE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "SYSTEM" ;