  CREATE TABLE "DBO"."AMP_COMMON_STATUS" 
   (	"STATUSID" NUMBER(10,0) NOT NULL ENABLE, 
	"STATUSTYPEID" NUMBER(10,0) NOT NULL ENABLE, 
	"CODE" VARCHAR2(10 BYTE) NOT NULL ENABLE, 
	"DESCRIPTION" VARCHAR2(40 BYTE) NOT NULL ENABLE, 
	"ENABLED" NUMBER(1,0) DEFAULT ((1)) NOT NULL ENABLE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
 ;