  CREATE TABLE "DBO"."AMP_COMMON_PAYMENTMETHOD" 
   (	"PAYMENTMETHODID" NUMBER(10,0) NOT NULL ENABLE, 
	"METHOD" NVARCHAR2(10) NOT NULL ENABLE, 
	"DESCRIPTION" NVARCHAR2(50) NOT NULL ENABLE, 
	"ISCOMMISSIONPAYMENTMETHOD" NUMBER(1,0) DEFAULT ((0))
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
 ;
