  CREATE TABLE "DBO"."AMP_AGT_ALIASTYPE" 
   (	"ALIASTYPEID" NUMBER(10,0) NOT NULL ENABLE, 
	"NAME" NVARCHAR2(50) NOT NULL ENABLE, 
	"DESCRIPTION" NVARCHAR2(100) NOT NULL ENABLE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
 ;