  CREATE TABLE "DBO"."AMP_AGT_AGENTCONTACT" 
   (	"AGENTCONTACTID" NUMBER(10,0) NOT NULL ENABLE, 
	"AGENTID" NUMBER(10,0) NOT NULL ENABLE, 
	"CONTACTBASEID" NUMBER(10,0) NOT NULL ENABLE, 
	"ACTIVE" NUMBER(1,0) DEFAULT ((1)) NOT NULL ENABLE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "SYSTEM" ;