  CREATE TABLE "DBO"."AMP_COMMON_ENTITY" 
   (	"ENTITYID" NUMBER(10,0) NOT NULL ENABLE, 
	"NAME" NVARCHAR2(50) NOT NULL ENABLE, 
	"DESCRIPTION" NVARCHAR2(50), 
	"CREATEDON" TIMESTAMP (3) DEFAULT (systimestamp), 
	"CREATEDBY" VARCHAR2(50 BYTE) DEFAULT (sys_context('userenv', 'os_user')), 
	"LASTUPDATEDON" TIMESTAMP (3), 
	"LASTUPDATEDBY" VARCHAR2(50 BYTE), 
	"ISCOMMISSIONABLE" NUMBER(1,0) DEFAULT ((0)) NOT NULL ENABLE, 
	"ISAUTOEMISION" NUMBER(1,0) DEFAULT ((0)) NOT NULL ENABLE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
 ;