  CREATE TABLE "DBO"."AMP_AGT_AGENTLEGACYNUMBERS" 
   (	"AGENTLEGACYNUMBERID" NUMBER(10,0) NOT NULL ENABLE, 
	"AGENTID" NUMBER(10,0) NOT NULL ENABLE, 
	"LEGACYNUMBER" NVARCHAR2(35) NOT NULL ENABLE, 
	"TYPEID" NUMBER(10,0)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "SYSTEM" ;