 CREATE TABLE "DBO"."AMP_AGT_AGENTALIAS" 
   (	"AGENTALIASID" NUMBER(10,0) NOT NULL ENABLE, 
	"AGENTHIERARCHYID" NUMBER(10,0) NOT NULL ENABLE, 
	"ALIASTYPEID" NUMBER(10,0) NOT NULL ENABLE, 
	"ALIAS" NVARCHAR2(50) NOT NULL ENABLE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "SYSTEM" ;