  CREATE TABLE "DBO"."AMP_GENERIC_ADDRESSTYPE" 
   (	"ADDRESSTYPEID" NUMBER(10,0) NOT NULL ENABLE, 
	"TYPENAME" NVARCHAR2(50) NOT NULL ENABLE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
 ;